config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :members
  resources :groups
  resources :locations
  resources :users
  resources :configuration_dates
  post "users/valid_update" , as: 'users_valid_update', to: 'users#valid_update'

end

app/views/common/_footer.html.erb
<script>
$(function() {
  $('#configuration_date').datepicker();
  $.datepicker.setDefaults( $.datepicker.regional[ "ja" ] );
});
</script>

app/views/common/_header.html.erb
<% if user_signed_in? %>
<div class="nohero">
  <header>
    <div class="container">
        <div class="container-small">
            <a href="index.html" class="headA">現場配置</a>

            <button type="button" class="headC">
                <span class="fa fa-bars" title="MENU"></span>
            </button>
        </div>

        <nav class="headB">
            <ul>
            <% if user_signed_in? %>
                <li><a href="/users/<%= current_user.id %>">マイページ</a></li>

                <% if current_user.admin_flg %>

                  <% if current_user.admin_flg == 1 %>

                    <li><%= link_to "ユーザ情報の編集", edit_user_path(current_user) %></li>
                    <li><%= link_to "会社情報の編集", edit_group_path(current_user) %></li>
                    <li><a href="/configuration_dates">配置の一覧</a></li>
                    <li><a href="/users">作業員の一覧</a></li>
                    <li><a href="/locations">作業場所の一覧</a></li>
                    <li><%= link_to "作業員を追加", new_member_path(current_user) %></li>
                    <li><%= link_to "作業場所を追加", new_location_path(current_user) %></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

                  <% elsif current_user.admin_flg == 0 %>

                    <li><%= link_to "ユーザ情報の編集", edit_user_path(current_user) %></li>

                    <% if current_user.valid_flg == 1 %>
                      <li><a href="/configuration_dates">配置の一覧</a></li>
                    <% end %>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

                  <% end %>

                <% else %>

                    <li><%= link_to "ユーザ情報の編集", edit_user_path(current_user) %></li>
                    <li><%= link_to "会社情報の編集", edit_group_path(current_user) %></li>
                    <li><a href="/configuration_dates">配置の一覧</a></li>
                    <li><a href="/users">作業員の一覧</a></li>
                    <li><a href="/locations">作業場所の一覧</a></li>
                    <li><%= link_to "作業員を追加", new_member_path(current_user) %></li>
                    <li><%= link_to "作業場所を追加", new_location_path(current_user) %></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

                <% end %>
            <% else %>
                <%= link_to "新規登録", new_user_registration_path %>
                <%= link_to "ログイン", new_user_session_path %>
            <% end %>
            </ul>
        </nav>
    </div>
  </header>
</div>

<% end %>